# Generated by Django 3.2.10 on 2023-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
