# Generated by Django 3.2.20 on 2023-07-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id']},
        ),
    ]
